export default {
  'modal-body-padding': '20px',
  'modal-header-bg': '#f5f5f5',
  'modal-header-title-line-height': '20px',
  'modal-header-title-font-size': '14px',
  'modal-header-close-size': '40px',
  'modal-header-padding': '14px 20px',
  'modal-header-border-width': '2px',
  'height-base': '32px',
  'primary-color': '#647BFC', // 全局主色
  'primary-color-hover': '#647BFC',
  'link-color': '#647BFC', // 链接色
  'btn-border-radius-base': '5px',
  'switch-height': '26px',
  'progress-default-color': '#647BFC',
  'dropdown-selected-color': 'd9ebff',
  'background-color-light': '#f1f4fe ',
  'item-hover-bg': '#f1f4fe',
  'table-padding-vertical': '5px',
  'switch-color': '#647BFC',
  'switch-bg': '#bbb',
  'processing-color': '#647BFC',
  'checkbox-check-bg': 'transparent',
  'pagination-item-bg-active': '#eaefff',
};
